version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Create File
          command: echo "This commit was created automatically again." > commit2.txt
      - run:
          name: Configure Git
          command: |
            git config --global user.email "kabiridorsa@gmail.com"
            git config --global user.name "Dorsa74"

      - run:
          name: Commit and Push Changes
          command: |
            git add commit2.txt
            git commit -m "Add commit file"
            git push origin main  
            
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 tests.py
      - run:
          name: List Contents of Directory
          command: ls -l /home/circleci/project/
      - store_artifacts:
          path: test-reports/
          destination: automation_testing
